[package]
name = "kansei-wasm-gi-box"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kansei-core = { path = "../../../kansei-core" }
kansei-wasm = { path = "../.." }
wgpu = { version = "24", features = ["webgpu"] }
glam = { version = "0.29", features = ["bytemuck"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
log = "0.4"

[workspace]
